/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.test {
    export class BigUI extends Laya.Scene {
		public _list:Laya.List;
        public static  uiView:any ={"type":"Scene","props":{"width":500,"height":700},"compId":2,"child":[{"type":"List","props":{"y":50,"x":5,"width":490,"var":"_list","vScrollBarSkin":" ","spaceY":0,"selectEnable":false,"repeatX":1,"height":600},"compId":3,"child":[{"type":"bigItem","props":{"runtime":"view/bigItem.ts","renderType":"render"},"compId":5}]}],"loadList":[],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(BigUI.uiView);
        }
    }
    REG("ui.test.BigUI",BigUI);
    export class BigItemUI extends Laya.View {
		public img_head:Laya.Image;
		public text_number:Laya.Label;
		public text_name:Laya.Label;
		public text_score:Laya.Label;
        public static  uiView:any ={"type":"View","props":{"width":480,"height":100},"compId":2,"child":[{"type":"Sprite","props":{"y":0,"x":40,"texture":"rank/Separator.png"},"compId":7},{"type":"Image","props":{"y":10,"x":76,"width":80,"var":"img_head","skin":"rank/cube.png","height":80},"compId":3,"child":[{"type":"Sprite","props":{"y":0,"x":0,"width":80,"texture":"rank/c1.png","renderType":"mask","height":80},"compId":10}]},{"type":"Label","props":{"y":0,"x":0,"width":76,"var":"text_number","valign":"middle","text":"#99","height":100,"fontSize":30,"color":"#4e2623","bold":true,"align":"center"},"compId":11},{"type":"Label","props":{"y":0,"x":169,"width":199,"var":"text_name","valign":"middle","text":"名字","overflow":"scroll","height":100,"fontSize":25,"color":"#4e2623","bold":true,"align":"left"},"compId":4},{"type":"Label","props":{"y":0,"x":361,"width":119,"var":"text_score","valign":"middle","text":"13.45","height":100,"fontSize":30,"color":"#08bf76","bold":true,"align":"center"},"compId":5}],"loadList":["rank/Separator.png","rank/cube.png","rank/c1.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(BigItemUI.uiView);
        }
    }
    REG("ui.test.BigItemUI",BigItemUI);
}